version: '3'

services:
  kloud_redis:
    image: redis:latest
    ports:
      - "6379:6379"
  kloud_fast_api:
    build: .
    depends_on:
      - kloud_redis
      - kloud_celery
    command: python /app/server.py
  kloud_celery:
    build: ./server/app/data_analysis
    depends_on:
      - kloud_redis
    command: celery -A data_worker worker -l info
